name: grab email accounts from @XX.com
on:
  workflow_dispatch:
    inputs:
      URL:
        description: your target email suffix like this "@XX.com"
        type: enviroment
        required: true
      proxy:
        description: proxy string like "socks5://127.0.0.1"
        type: string
        required: true
      filename:
        description: domain list text file name
        type: string
        required: true        
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update      
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run demo
        run: |
          bash run.sh
        env:
          URL: '${{ github.event.inputs.URL }}'
          proxy: '${{ github.event.inputs.proxy }}'
          filename: '${{ github.event.inputs.filename }}'

      - name: Config git
        run: >
          git config --local user.email "ations@github.com"

          git config --local user.name "github"

          git config --global http.postBuffer 157286400

          git remote set-url origin "https://${{ github.actor }}:${{
          github.token }}@github.com/${{ github.repository }}"
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ github.run_id }}'
          prerelease: false
          title: '${{ github.run_id }}'
          files: |
            result/*
